"""add tags to analysis

Revision ID: cd83af85c2db
Revises: aa06adfddcd5
Create Date: 2026-03-07 10:51:08.982126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd83af85c2db'
down_revision: Union[str, Sequence[str], None] = 'aa06adfddcd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('tags', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'tags')
    # ### end Alembic commands ###
